name: 'mds4all'
version: '1.0.0'
config-version: 2

profile: 'mds4all'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:
    - "target"
    - "dbt_modules"

models:
  mds4all:
    materialized: table
