name: run_elt

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

env:
  DBT_PROFILES_DIR: ./
  BIGQUERY_PROJECT: mds4all
  BIGQUERY_DATASET: analytics
  BIGQUERY_KEYFILE_PATH: ./bigquery-sa.json

jobs:
  run_elt:
    name: run_elt
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"

      - name: Write creds keyfile to BigQuery
        run: 'echo "$KEYFILE" > $BIGQUERY_KEYFILE_PATH'
        shell: bash
        env:
          KEYFILE: ${{ secrets.BIGQUERY_KEYFILE }}

      - name: Install meltano dependencies
        run: |
          pip install meltano
          meltano install extractor tap-spreadsheets-anywhere
          meltano install loader target-bigquery

      - name: Run meltano
        run: meltano elt tap-spreadsheets-anywhere target-bigquery

      - name: Install dbt dependencies
        run: |
          pip install dbt-bigquery
          dbt deps
      
      - name: Run dbt models
        run: dbt run

      - name: Test dbt models
        run: dbt test

      - name: Generate docs
        run: dbt docs generate
        uses: actions/upload-artifact@v2
        with:
          name: dbt-docs
          path: docs
